name: "GitHub Action for Creating Kind (Kubernetes in Docker) Clusters"
description: "Create a kind cluster"
author: "The Helm authors"
branding:
  color: blue
  icon: check-circle
inputs:
  version:
    description: "The kind version to use (default: v0.5.1)"
  config:
    description: "The path to the kind config file"
  node_image:
    description: "The Docker image for the cluster nodes"
  cluster_name:
    description: "The name of the cluster to create (default: chart-testing)"
  wait:
    description: "The duration to wait for the control plane to become ready (default: 60s)"
  log_level:
    description: "The log level for kind"
  install_local_path_provisioner:
    description: |
      If true, Rancher's local-path provisioner is installed which supports
      dynamic volume provisioning on multi-node clusters. The newly created
      local-path StorageClass is made the default.
runs:
  using: "node12"
  main: "main.js"
