name: "Kind Cluster"
description: "Create a kind (Kubernetes IN Docker) cluster"
author: "The Helm authors"
branding:
  color: blue
  icon: box
inputs:
  version:
    description: "The kind version to use (default: v0.26.0)"
    required: false
    default: "v0.26.0"
  config:
    description: "The path to the kind config file"
    required: false
  kubeconfig:
    description: "The path to the kubeconfig config file"
    required: false
  node_image:
    description: "The Docker image for the cluster nodes"
    required: false
  cluster_name:
    description: "The name of the cluster to create (default: chart-testing)"
    required: false
    default: "chart-testing"
  wait:
    description: "The duration to wait for the control plane to become ready (default: 60s)"
    required: false
    default: "60s"
  verbosity:
    description: "The verbosity level for kind (default: 0)"
    default: "0"
    required: false
  kubectl_version:
    description: "The kubectl version to use (default: v1.31.4)"
    required: false
    default: "v1.31.4"
  registry:
    description: "Whether to configure an insecure local registry (default: false)"
    required: false
    default: "false"
  registry_image:
    description: "The registry image to use (default: registry:2)"
    required: false
    default: "registry:2"
  registry_name:
    description: "The registry name to use (default: kind-registry)"
    required: false
    default: "kind-registry"
  registry_port:
    description: "The local port used to bind the registry (default: 5000)"
    required: false
    default: "5000"
  registry_enable_delete:
    description: "Enable delete operations on the registry (default: false)"
    required: false
    default: "false"
  install_only:
    description: "Skips cluster creation, only install kind (default: false)"
    required: false
  ignore_failed_clean:
    description: "Whether to ignore the post-delete the cluster (default: false)"
    default: "false"
    required: false
runs:
  using: "node20"
  main: "main.js"
  post: "cleanup.js"
